### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by Unitech** [pm2-hive/pm2-php-fpm#1]
When I try to do a pm2 install pm2-php-fpm, the module does not start and I get the following error:

```
pm2-php-fpm-10 (err): Error: Cannot find module 'babel/polyfill'
pm2-php-fpm-10 (err):     at Function.Module._resolveFilename (module.js:336:15)
pm2-php-fpm-10 (err):     at Function.Module._load (module.js:286:25)
pm2-php-fpm-10 (err):     at Function._load (/home/node/.nvm/versions/node/v4.0.0/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
pm2-php-fpm-10 (err):     at Module.require (module.js:365:17)
pm2-php-fpm-10 (err):     at require (module.js:384:17)
pm2-php-fpm-10 (err):     at Object.<anonymous> (/home/node/.pm2/node_modules/pm2-php-fpm/lib/app.js:5:1)
pm2-php-fpm-10 (err):     at Module._compile (module.js:434:26)
pm2-php-fpm-10 (err):     at Object.Module._extensions..js (module.js:452:10)
pm2-php-fpm-10 (err):     at Module.load (module.js:355:32)
pm2-php-fpm-10 (err):     at Function.Module._load (module.js:310:12)
```

@kinday

**Comment by kinday** [comment]
Sorry for this little, yet annoying bug. It’s fixed in `v0.0.1`

**Comment by Unitech** [comment]
Thanks @kinday!
@alavit-d could you publish the module? thanks

**Comment by alavit-d** [comment]
New version published
