### ISSUE TITLE
ReferenceError: fcgi is not defined

### ISSUE THREAD

**Issue by ed-fruty** [pm2-hive/pm2-php-fpm#8]
```bash
0|pm2-php-fpm  | ReferenceError: fcgi is not defined
0|pm2-php-fpm  |     at new Stats (/home/user/.pm2/modules/pm2-php-fpm/node_modules/pm2-php-fpm/lib/monitor.js:44:13)
0|pm2-php-fpm  |     at /home/user/.pm2/modules/pm2-php-fpm/node_modules/pm2-php-fpm/lib/app.js:40:17
0|pm2-php-fpm  |     at Object.PMX.initModule (/home/user/.pm2/modules/pm2-php-fpm/node_modules/pmx/lib/pmx.js:145:12)
0|pm2-php-fpm  |     at Object.<anonymous> (/home/user/.pm2/modules/pm2-php-fpm/node_modules/pm2-php-fpm/lib/app.js:19:18)
0|pm2-php-fpm  |     at Module._compile (internal/modules/cjs/loader.js:945:30)
0|pm2-php-fpm  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
0|pm2-php-fpm  |     at Module.load (internal/modules/cjs/loader.js:798:32)
0|pm2-php-fpm  |     at Function.Module._load (internal/modules/cjs/loader.js:711:12)
0|pm2-php-fpm  |     at Module.require (internal/modules/cjs/loader.js:838:19)
0|pm2-php-fpm  |     at Module.Hook._require.Module.require (/home/user/.nvm/versions/node/v12.11.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
PM2            | App [pm2-php-fpm:0] exited with code [1] via signal [SIGINT]
PM2            | Script /home/user/.pm2/modules/pm2-php-fpm/node_modules/pm2-php-fpm/index.js had too many unstable restarts (16). Stopped. "errored"
```

**Comment by olddeda** [comment]
ReferenceError: fcgi is not defined

**Comment by selfagency** [comment]
Still

**Comment by solokhind** [comment]
Having the same issue with PHP7.4-FPM
